import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from "@/components/ui/button";
import { ArrowLeft, Cookie } from "lucide-react";
import { ScrollArea } from "@/components/ui/scroll-area";

export default function CookiePolicy() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col">
      <nav className="border-b bg-white px-6 h-16 flex items-center shrink-0 sticky top-0 z-10">
        <Button variant="ghost" onClick={() => navigate(-1)} className="mr-4 -ml-2 text-slate-500">
          <ArrowLeft className="w-4 h-4 mr-2" /> Back
        </Button>
        <div className="flex items-center gap-2">
          <Cookie className="w-5 h-5 text-indigo-600" />
          <span className="font-bold text-slate-900">MEVS Platform</span>
        </div>
      </nav>

      <div className="flex-1 max-w-4xl w-full mx-auto p-6 md:p-12">
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-8 md:p-12">
          <h1 className="text-3xl font-black tracking-tight text-slate-900 mb-2">Cookie Policy</h1>
          <p className="text-sm text-slate-500 mb-8 pb-8 border-b border-slate-100">Last updated: {new Date().toLocaleDateString()}</p>

          <ScrollArea className="h-[60vh] pr-6">
            <div className="prose prose-slate prose-sm max-w-none space-y-6">
              <section>
                <h2 className="text-lg font-bold text-slate-800 uppercase tracking-wide">1. What Are Cookies</h2>
                <p className="text-slate-600 leading-relaxed">
                  Cookies are small text files that are stored on your device when you visit our platform. They are essential for maintaining your secure session and authenticating you with our database.
                </p>
              </section>

              <section>
                <h2 className="text-lg font-bold text-slate-800 uppercase tracking-wide">2. How We Use Cookies</h2>
                <p className="text-slate-600 leading-relaxed">
                  MEVS exclusively uses <strong>Strictly Necessary Cookies</strong>. We use cookies generated by Supabase to maintain your authentication state securely (e.g., JWT tokens). Without these cookies, you cannot log into your enterprise dashboard.
                </p>
              </section>

              <section>
                <h2 className="text-lg font-bold text-slate-800 uppercase tracking-wide">3. Third-Party Tracking</h2>
                <p className="text-slate-600 leading-relaxed">
                  We value your privacy. We use privacy-focused analytics (Plausible) which does <strong>not</strong> use tracking cookies or track IP addresses across devices. 
                </p>
              </section>

              <section>
                <h2 className="text-lg font-bold text-slate-800 uppercase tracking-wide">4. Managing Cookies</h2>
                <p className="text-slate-600 leading-relaxed">
                  Because our cookies are strictly necessary for the application to function, they cannot be turned off in our systems. You can set your browser to block or alert you about these cookies, but some parts of the site will not work.
                </p>
              </section>
            </div>
          </ScrollArea>
        </div>
      </div>
    </div>
  );
}
