import React, { useMemo, useState } from 'react';
import { Download, Edit2, Eye, FileText, Plus, Power, Search, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { api } from '@/lib/apiClient';
import { useConfirmation } from '@/hooks/useConfirmation';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { barItemsCsv, filterBarItems } from '@/modules/recipes/lib/barItemsDomain';

const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' });

export default function BarItemsOperations({ recipes, recipeTypes, onAdd, onView, onEdit, onChanged }) {
  const { confirm } = useConfirmation();
  const [filters, setFilters] = useState({ search: '', type: 'all', alert: 'all', status: 'active' });
  const [selected, setSelected] = useState([]);
  const beverageTypes = useMemo(() => (recipeTypes || []).filter((row) => row.kind === 'beverage'), [recipeTypes]);
  const typeIds = useMemo(() => beverageTypes.map((row) => row.id), [beverageTypes]);
  const typeMap = useMemo(() => new Map(beverageTypes.map((row) => [row.id, row.name])), [beverageTypes]);
  const items = useMemo(() => filterBarItems(recipes, filters, typeIds), [recipes, filters, typeIds]);
  const set = (key, value) => setFilters((current) => ({ ...current, [key]: value }));
  const exportCsv = () => { const rows = selected.length ? items.filter((row) => selected.includes(row.id)) : items; const url = URL.createObjectURL(new Blob([barItemsCsv(rows, typeMap)], { type: 'text/csv' })); const a = document.createElement('a'); a.href = url; a.download = 'bar-items.csv'; a.click(); URL.revokeObjectURL(url); };
  const toggleStatus = async (item) => { const activate = item.status !== 'active'; const ok = await confirm({ title: `${activate ? 'Activate' : 'Deactivate'} ${item.name}?`, description: activate ? 'The Bar Item will become available for restaurant use.' : 'Existing recipe references remain intact, but the Bar Item will be hidden from active selection.', confirmText: activate ? 'Activate' : 'Deactivate', variant: 'warning', severity: 'high' }); if (!ok) return; try { await api.recipes.setBarItemStatus(item.id, activate ? 'active' : 'inactive'); toast.success(`Bar Item ${activate ? 'activated' : 'deactivated'}`); onChanged(); } catch (error) { toast.error(error.message || 'Unable to change Bar Item status'); } };
  const remove = async (item) => { let dependencies = []; try { dependencies = await api.recipes.getPreparedItemDependencies(item.id); } catch { /* graceful migration fallback */ } if (dependencies.length) { toast.error(`${item.name} is used in ${dependencies.length} recipe${dependencies.length === 1 ? '' : 's'} and cannot be deleted.`); return; } const ok = await confirm({ title: `Delete ${item.name}?`, description: 'This permanently removes the unused Bar Item and its Recipe costing history.', confirmText: 'Delete Bar Item', variant: 'destructive', severity: 'critical' }); if (!ok) return; try { await api.recipes.deleteBarItem(item.id); toast.success('Bar Item deleted'); onChanged(); } catch (error) { toast.error(error.message || 'Unable to delete Bar Item'); } };
  return <div className="space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-semibold">Bar Items</h1><p className="text-sm text-muted-foreground">Beverage recipes with tenant-scoped pour-cost and selling economics.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => window.print()}><FileText className="mr-2 h-4 w-4"/>Print</Button><Button variant="outline" onClick={exportCsv}><Download className="mr-2 h-4 w-4"/>Export CSV</Button><Button onClick={onAdd}><Plus className="mr-2 h-4 w-4"/>Add Bar Item</Button></div></div>
    <Card><CardContent className="grid gap-3 p-4 lg:grid-cols-[1fr_210px_180px_170px]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" placeholder="Search Bar Items" value={filters.search} onChange={(e) => set('search', e.target.value)}/></div><Select value={filters.type} onValueChange={(value) => set('type', value)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All beverage types</SelectItem>{beverageTypes.map((row) => <SelectItem key={row.id} value={row.id}>{row.name}</SelectItem>)}</SelectContent></Select><Select value={filters.alert} onValueChange={(value) => set('alert', value)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All alerts</SelectItem><SelectItem value="active">Active alerts</SelectItem><SelectItem value="paused">Paused alerts</SelectItem><SelectItem value="none">No alerts</SelectItem></SelectContent></Select><Select value={filters.status} onValueChange={(value) => set('status', value)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem><SelectItem value="active">Active</SelectItem><SelectItem value="inactive">Inactive</SelectItem></SelectContent></Select></CardContent></Card>
    <Card><CardHeader className="flex-row items-center justify-between"><CardTitle className="text-base">Beverage recipe library</CardTitle><span className="text-sm text-muted-foreground">{items.length} item{items.length === 1 ? '' : 's'}</span></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead className="w-12"><Checkbox checked={items.length > 0 && selected.length === items.length} onCheckedChange={(checked) => setSelected(checked ? items.map((row) => row.id) : [])}/></TableHead><TableHead>Name</TableHead><TableHead>Type</TableHead><TableHead>Status</TableHead><TableHead>Cost / serving</TableHead><TableHead>Selling price</TableHead><TableHead>Pour cost</TableHead><TableHead>Gross profit</TableHead><TableHead>Alert</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{items.length ? items.map((item) => { const price = Number(item.selling_price || 0); const cost = Number(item.cost_per_serving || 0); return <TableRow key={item.id}><TableCell><Checkbox checked={selected.includes(item.id)} onCheckedChange={(checked) => setSelected(checked ? [...new Set([...selected, item.id])] : selected.filter((id) => id !== item.id))}/></TableCell><TableCell className="font-medium">{item.name}</TableCell><TableCell><Badge variant="secondary">{typeMap.get(item.recipe_type_id) || 'Other'}</Badge></TableCell><TableCell className="capitalize">{item.status}</TableCell><TableCell>{money.format(cost)}</TableCell><TableCell>{price > 0 ? money.format(price) : 'Not set'}</TableCell><TableCell>{price > 0 ? `${(cost / price * 100).toFixed(1)}%` : '—'}</TableCell><TableCell>{price > 0 ? money.format(price - cost) : '—'}</TableCell><TableCell className="capitalize">{item.margin_alert_status || (item.margin_alert_enabled ? 'active' : 'none')}</TableCell><TableCell><div className="flex justify-end gap-1"><Button size="icon" variant="ghost" aria-label={`View ${item.name}`} onClick={() => onView(item)}><Eye className="h-4 w-4"/></Button><Button size="icon" variant="ghost" aria-label={`Edit ${item.name}`} onClick={() => onEdit(item)}><Edit2 className="h-4 w-4"/></Button><Button size="icon" variant="ghost" aria-label={`${item.status === 'active' ? 'Deactivate' : 'Activate'} ${item.name}`} onClick={() => toggleStatus(item)}><Power className="h-4 w-4"/></Button><Button size="icon" variant="ghost" aria-label={`Delete ${item.name}`} onClick={() => remove(item)}><Trash2 className="h-4 w-4"/></Button></div></TableCell></TableRow>; }) : <TableRow><TableCell colSpan={10} className="py-10 text-center text-muted-foreground">No Bar Items match these filters.</TableCell></TableRow>}</TableBody></Table></CardContent></Card>
  </div>;
}
